language: android
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra
os: linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone -b stable https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script:
  - cd twotwotap
  - flutter build apk
cache:
  directories:
    - $HOME/.pub-cach